#!/usr/bin/env python3

from pandocfilters import toJSONFilter, CodeBlock
from subprocess import check_output


def execute(key, value, format, meta):
    if key == "CodeBlock":
        [[id, cls, namevals], content] = value
        if 'do-exec' in cls:
            content = check_output(['bash'], input=content, shell=True,
                                   universal_newlines=True)
            return CodeBlock([id, cls, namevals], content)


if __name__ == '__main__':
    toJSONFilter(execute)
